---
fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    deploy_pe: "https://github.com/jarretlavallee/puppet-deploy_pe"
    ruby_plugin_helper:
      repo: "puppetlabs/ruby_plugin_helper"
      ref: "0.2.0"
  forge_modules:
    ruby_task_helper: "puppetlabs/ruby_task_helper"
    stdlib: "puppetlabs/stdlib"
    ruby_plugin_helper:
      repo: "puppetlabs/ruby_plugin_helper"
      ref: "0.2.0"
