---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  use_litmus: true
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  simplecov: true
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
Rakefile:
  requires:
  - puppet-lint/tasks/puppet-lint
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true