name: "acceptance"

on:
  push:
    branches:
      - feature_*

jobs:
  setup_vm:
    name: Setup Vm with mock webserver for installs script
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Activate Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: print file info
        run: |
          pwd
          ls -lh
      
      - name: Create webserver
        run: |
          mkdir ./web
          cd ./web
          wget https://github.com/rif/spark/releases/download/v1.8.1/spark_1.8.1_linux_amd64.tar.gz
          tar -xf spark_1.8.1_linux_amd64.tar.gz
          openssl req -x509 -sha256 -nodes -newkey rsa:2048 -days 365 -keyout localhost.key -out localhost.crt -subj '/CN=localhost/O=Testing/C=US'
          cp ${{ github.workspace }}/files/install.bash ./
          nohup ./spark -port 8141 -sslPort 8140 -path /packages/current/ -key localhost.key -cert localhost.crt & 

      - name: check webserver
        run: | 
          pwd
          curl https://localhost:8140/packages/current/install.bash -k

  Integration:
    needs:
      - setup_vm
    runs-on: ubuntu-22.04
    # if: ${{ needs.setup_vm.outputs.matrix != '{}' }}
    # strategy:
    #   fail-fast: false
    #   matrix: ${{fromJson(needs.setup_vm.outputs.matrix)}}

    env:
      PUPPET_GEM_VERSION: '~> 7.24'
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'  # why is this set?


    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Activate Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: Create the fixtures directory
        run: |
          bundle exec rake spec_prep

      - name: check if bolt available
        run: | 
          sudo /opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle exec bolt --modulepath spec/fixtures/modules task show
          ls -lh spec/fixtures/modules

      - name: check user running as
        run: | 
          id
          sudo bash
          id
          sudo cat /etc/sudoers
          which bundle
      
      - name: run bootstrap task
        run: |
          sudo /opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle exec bolt --modulepath spec/fixtures/modules task run bootstrap --targets localhost master=losthost certname=testing123.com