name: "acceptance"

on:
  push:
    branches:
      - feature_*

jobs:
  setup_vm:
    name: Run npm on Ubuntu
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: Activate Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: print file info
        run: |
          pwd
          ls -lh
